language: cpp
dist: xenial
osx_image: xcode10.1

env:
  global:
    - SCONS_CACHE="$HOME/.scons_cache"
    - SCONS_CACHE_LIMIT=1024

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - name: Linux Debug + Static Checks
      os: linux
      compiler: gcc
      env: TARGET=debug STATIC_CHECKS=yes ADDITIONAL_FLAGS="bits=64"
      addons:
        apt:
          packages:
            - clang-format-8
            - [scons, pkg-config, build-essential, p7zip-full]

    - name: Linux Release
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - [scons, pkg-config, build-essential, p7zip-full]
      env: TARGET=release ADDITIONAL_FLAGS="bits=64"

    - name: macOS Debug
      os: osx
      compiler: clang
      env: TARGET=debug ADDITIONAL_FLAGS="bits=64"

    - name: macOS Release
      os: osx
      compiler: clang
      env: TARGET=release ADDITIONAL_FLAGS="bits=64"

    - name: Windows MSVC Debug
      os: windows
      env: TARGET=debug ADDITIONAL_FLAGS="bits=64"

    - name: Windows MSVC Release
      os: windows
      env: TARGET=release ADDITIONAL_FLAGS="bits=64"

    - name: Android ARM Release
      os: linux
      env: TARGET=release ADDITIONAL_FLAGS="platform=android android_arch=armv7" PLATFORM="android" ANDROID_NDK_ROOT="/home/travis/build/godotengine/godot-cpp/ndk-bundle"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            [scons, pkg-config, build-essential, p7zip-full, clang-format-6.0]

    - name: Android ARM64 Release
      os: linux
      env: TARGET=release ADDITIONAL_FLAGS="platform=android android_arch=arm64v8" PLATFORM="android" ANDROID_NDK_ROOT="/home/travis/build/godotengine/godot-cpp/ndk-bundle"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            [scons, pkg-config, build-essential, p7zip-full, clang-format-6.0]

    - name: Android ARM Debug
      os: linux
      env: TARGET=debug ADDITIONAL_FLAGS="platform=android android_arch=armv7" PLATFORM="android" ANDROID_NDK_ROOT="/home/travis/build/godotengine/godot-cpp/ndk-bundle"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            [scons, pkg-config, build-essential, p7zip-full, clang-format-6.0]

    - name: Android ARM64 Debug
      os: linux
      env: TARGET=debug ADDITIONAL_FLAGS="platform=android android_arch=arm64v8" PLATFORM="android" ANDROID_NDK_ROOT="/home/travis/build/godotengine/godot-cpp/ndk-bundle"
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            [scons, pkg-config, build-essential, p7zip-full, clang-format-6.0]

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install scons p7zip;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      curl -LO https://downloads.sourceforge.net/project/scons/scons-local/3.1.2/scons-local-3.1.2.zip;
      unzip scons-local-3.1.2.zip;
    fi

  - if [[ "$PLATFORM" == "android" ]]; then
      sh .travis/download_android_ndk.sh;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export SCONS="./scons.bat";
    else
      export SCONS="scons";
    fi

  - $SCONS target="$TARGET" generate_bindings=yes $SCONS_FLAGS $ADDITIONAL_FLAGS;

  - if [[ "$STATIC_CHECKS" == "yes" ]]; then
      sh ./misc/travis/clang-format.sh;
    fi
